-- Generated by Awesome Menu Generator
-- Based on LXMED http://lxmed.sourceforge.net/ project
module("applicationsmenu")

applicationsmenu = {}

applicationsmenu[10] = {
{[====[7-Zip FM]====], [====[7zFM]====]},
{[====[About Xfce]====], [====[xfce4-about]====]},
{[====[Archive Manager]====], [====[file-roller]====]},
{[====[Bluetooth Transfer]====], [====[bluetooth-sendto]====]},
{[====[Caribou]====], [====[caribou]====]},
{[====[compton]====], [====[compton]====]},
{[====[Desktop Search]====], [====[tracker-needle]====]},
{[====[Docky]====], [====[docky]====]},
{[====[Documents]====], [====[gnome-documents]====]},
{[====[File Manager]====], [====[exo-open --launch FileManager %u]====]},
{[====[File Manager PCManFM]====], [====[pcmanfm]====]},
{[====[Files]====], [====[nautilus]====]},
{[====[Help]====], [====[yelp %u]====]},
{[====[Root Terminal]====], [====[gksu -l gnome-terminal]====]},
{[====[Terminal]====], [====[gnome-terminal]====]},
{[====[Terminal Emulator]====], [====[exo-open --launch TerminalEmulator]====]},
{[====[Tweak Tool]====], [====[gnome-tweak-tool]====]}
}
applicationsmenu[20] = {
}
applicationsmenu[30] = {
{[====[Dungeon Crawl Stone Soup]====], [====[crawl-tiles]====]}
}
applicationsmenu[40] = {
{[====[Feh]====], [====[feh %f]====]},
{[====[Font Manager]====], [====[font-manager]====]},
{[====[Font Sampler]====], [====[font-sampler]====]},
{[====[Image Viewer]====], [====[eog]====]}
}
applicationsmenu[50] = {
{[====[Avahi SSH Server Browser]====], [====[/usr/bin/bssh]====]},
{[====[Avahi VNC Server Browser]====], [====[/usr/bin/bvnc]====]},
{[====[Chromium]====], [====[chromium]====]},
{[====[Dropbox]====], [====[dropboxd]====]},
{[====[ELinks]====], [====[/usr/bin/elinks %u]====]},
{[====[Friends]====], [====[steam steam://open/friends]====]},
{[====[Mail Reader]====], [====[exo-open --launch MailReader %u]====]},
{[====[Pidgin Internet Messenger]====], [====[pidgin]====]},
{[====[Skype]====], [====[skype]====]},
{[====[Web]====], [====[epiphany]====]},
{[====[Web Browser]====], [====[exo-open --launch WebBrowser %u]====]},
{[====[Wicd]====], [====[/usr/bin/wicd-client]====]},
{[====[YouTube to Mp3]====], [====[YouTubeToMP3]====]}
}
applicationsmenu[60] = {
{[====[Document Viewer]====], [====[evince]====]},
{[====[Evolution]====], [====[evolution]====]},
{[====[LibreOffice]====], [====[libreoffice]====]},
{[====[New Database]====], [====[libreoffice --base]====]},
{[====[New Document]====], [====[libreoffice --writer]====]},
{[====[New Drawing]====], [====[libreoffice --draw]====]},
{[====[New Formula]====], [====[libreoffice --math]====]},
{[====[New Presentation]====], [====[libreoffice --impress]====]},
{[====[New Spreadsheet]====], [====[libreoffice --calc]====]},
{[====[Print Preview]====], [====[evince-previewer]====]},
{[====[Xpdf]====], [====[xpdf %f]====]}
}
applicationsmenu[70] = {
{[====[Access Prompt]====], [====[/usr/lib/gcr/gcr-prompter]====]},
{[====[Connect to Server]====], [====[nautilus-connect-server]====]},
{[====[Evolution Calendar]====], [====[evolution -c calendar]====]},
{[====[GNOME Shell]====], [====[/usr/bin/gnome-shell]====]},
{[====[GNOME Shell Extension Preferences]====], [====[/usr/bin/gnome-shell-extension-prefs %u]====]},
{[====[LibreOffice XSLT based filters]====], [====[libreoffice]====]},
{[====[Menu Editor]====], [====[gmenu-simple-editor]====]},
{[====[Metacity]====], [====[metacity]====]},
{[====[Muffin]====], [====[muffin]====]},
{[====[Mutter]====], [====[mutter]====]},
{[====[Network]====], [====[nm-applet]====]},
{[====[Notification Daemon]====], [====[/usr/lib/notification-daemon-1.0/notification-daemon]====]},
{[====[Openbox]====], [====[openbox]====]},
{[====[Run Software]====], [====[nautilus-autorun-software %u]====]},
{[====[View file]====], [====[/usr/bin/gcr-viewer]====]}
}
applicationsmenu[80] = {
{[====[CMake]====], [====[cmake-gui %f]====]},
{[====[Elementary Test]====], [====[elementary_test]====]},
{[====[OpenJDK Monitoring & Management Console]====], [====[/usr/bin/jconsole]====]},
{[====[OpenJDK Policy Tool]====], [====[/usr/bin/policytool]====]},
{[====[Qt4 Assistant]====], [====[assistant-qt4]====]},
{[====[Qt4 Designer]====], [====[designer-qt4]====]},
{[====[Qt4 Linguist]====], [====[linguist-qt4]====]}
}
applicationsmenu[90] = {
{[====[Gnome Music Player Client]====], [====[gmpc]====]},
{[====[Google Music Manager]====], [====[/opt/google/musicmanager/google-musicmanager]====]},
{[====[MPlayer]====], [====[mplayer %F]====]},
{[====[MPlayer Media Player]====], [====[mplayer %F]====]},
{[====[Open in standalone mode]====], [====[xbmc --standalone]====]},
{[====[QT V4L2 test Utility]====], [====[qv4l2]====]},
{[====[VLC media player]====], [====[/usr/bin/vlc]====]},
{[====[Xmms2Tray]====], [====[xmms2tray]====]}
}
applicationsmenu[100] = {
{[====[Avahi Zeroconf Browser]====], [====[/usr/bin/avahi-discover]====]},
{[====[Batti]====], [====[batti]====]},
{[====[Bulk Rename]====], [====[/usr/lib/Thunar/ThunarBulkRename %F]====]},
{[====[Cerbere]====], [====[cerbere]====]},
{[====[Cinnamon]====], [====[/usr/bin/cinnamon]====]},
{[====[Cinnamon 2D]====], [====[/usr/bin/cinnamon2d]====]},
{[====[dconf Editor]====], [====[dconf-editor]====]},
{[====[Guake Terminal]====], [====[guake]====]},
{[====[Htop]====], [====[htop]====]},
{[====[IBus]====], [====[ibus-daemon --xim]====]},
{[====[Keyboard Layout]====], [====[gkbd-keyboard-display]====]},
{[====[Open Folder with Thunar]====], [====[thunar %F]====]},
{[====[Panel]====], [====[gnome-panel]====]},
{[====[System Monitor]====], [====[gnome-system-monitor]====]},
{[====[System Settings]====], [====[cinnamon-settings]====]},
{[====[System Settings]====], [====[gnome-control-center --overview]====]},
{[====[Thunar File Manager]====], [====[thunar %F]====]},
{[====[urxvt]====], [====[urxvt]====]},
{[====[urxvt (client)]====], [====[urxvtc]====]},
{[====[urxvt (tabbed)]====], [====[urxvt-tabbed]====]},
{[====[UXTerm]====], [====[uxterm]====]},
{[====[XTerm]====], [====[xterm]====]}
}
applicationsmenu[110] = {
{[====[Adobe Flash Player]====], [====[flash-player-properties]====]},
{[====[Background]====], [====[gnome-control-center background]====]},
{[====[Bluetooth]====], [====[gnome-control-center bluetooth]====]},
{[====[Bluetooth Device Setup]====], [====[bluetooth-wizard]====]},
{[====[Brightness & Lock]====], [====[gnome-control-center screen]====]},
{[====[Cinnamon Menu Editor]====], [====[cinnamon-menu-editor]====]},
{[====[Color]====], [====[gnome-control-center color]====]},
{[====[Customize Look and Feel]====], [====[lxappearance]====]},
{[====[Date & Time]====], [====[gnome-control-center datetime]====]},
{[====[Desktop Preferences]====], [====[pcmanfm --desktop-pref]====]},
{[====[Details]====], [====[gnome-control-center info]====]},
{[====[Displays]====], [====[gnome-control-center display]====]},
{[====[Elementary Configuration]====], [====[elementary_config]====]},
{[====[File Manager]====], [====[thunar-settings]====]},
{[====[Guake Preferences]====], [====[guake-prefs]====]},
{[====[IBus Preferences]====], [====[ibus-setup]====]},
{[====[Keyboard]====], [====[gnome-control-center keyboard]====]},
{[====[Main Menu]====], [====[alacarte]====]},
{[====[Mouse & Touchpad]====], [====[gnome-control-center mouse]====]},
{[====[Network]====], [====[gnome-control-center network]====]},
{[====[Network Connections]====], [====[nm-connection-editor]====]},
{[====[Online Accounts]====], [====[gnome-control-center online-accounts]====]},
{[====[Openbox Configuration Manager]====], [====[obconf %f]====]},
{[====[Panel Launcher Editor]====], [====[/usr/share/cinnamon/applets/panel-launchers@cinnamon.org/cinnamon-add-panel-launcher.py]====]},
{[====[Panel tint2]====], [====[tint2conf]====]},
{[====[Power]====], [====[gnome-control-center power]====]},
{[====[Preferred Applications]====], [====[exo-preferred-applications]====]},
{[====[Preferred Applications]====], [====[libfm-pref-apps]====]},
{[====[Printers]====], [====[gnome-control-center printers]====]},
{[====[Privilege granting]====], [====[gksu-properties]====]},
{[====[Qt4 Config]====], [====[qtconfig-qt4]====]},
{[====[Region & Language]====], [====[gnome-control-center region]====]},
{[====[Search and Indexing]====], [====[tracker-preferences]====]},
{[====[Sound]====], [====[gnome-control-center sound]====]},
{[====[Startup Applications]====], [====[gnome-session-properties]====]},
{[====[Startup Applications]====], [====[gnome-session-properties]====]},
{[====[Universal Access]====], [====[gnome-control-center universal-access]====]},
{[====[User Accounts]====], [====[gnome-control-center user-accounts]====]},
{[====[Wacom Tablet]====], [====[gnome-control-center wacom]====]}
}

applicationsmenu[1] = {
{[====[Accessories]====], applicationsmenu[10]},
{[====[Education]====], applicationsmenu[20]},
{[====[Games]====], applicationsmenu[30]},
{[====[Graphics]====], applicationsmenu[40]},
{[====[Internet]====], applicationsmenu[50]},
{[====[Office]====], applicationsmenu[60]},
{[====[Other]====], applicationsmenu[70]},
{[====[Programming]====], applicationsmenu[80]},
{[====[Sound & Video]====], applicationsmenu[90]},
{[====[System Tools]====], applicationsmenu[100]},
{[====[Preferences]====], applicationsmenu[110]}
}

passed = applicationsmenu[1]
function applicationsmenu() return passed end
